export const images = {
    WELCOME_IMAGE1: require('../assets/Images/undraw_data_report_re_p4so.png'),
    WELCOME_IMAGE2: require('../assets/Images/undraw_online_groceries_a02y.png'),
    WELCOME_IMAGE3: require('../assets/Images/undraw_segmentation_re_gduq.png'),
    LOGIN_SCREEN: require('../assets/Images/Login_amico.png'),
    FORGOT_PASSWORD: require('../assets/Images/Forgot_password_pana.png'),
    OTP_SCREEN: require('../assets/Images/OTP_pana.png'),
    RESET_PASSWORD: require('../assets/Images/Reset_password_pana.png'),
    ORDER_IMAGE: require('../assets/DasboardIcons/order_image.png'),
    BG_IMAGE: require('../assets/DasboardIcons/backgroundImage.png'),
    NEW_ORDER: require('../assets/DasboardIcons/new-order.png'),
    SALES: require('../assets/DasboardIcons/increasing.png'),
    ORDER_BOX: require('../assets/DasboardIcons/order-delivery.png'),
    PRODUCTS: require('../assets/DasboardIcons/product_package.png'),
    CUSTOMERS: require('../assets/DasboardIcons/customer.png'),
    ADD: require('../assets/DasboardIcons/Add_icon.png'),
    MAIN_LOGO_IMAGE: require('../assets/DasboardIcons/ic_launcher_round.png'),
    SUPPLIERS_LOGO: require('../assets/DasboardIcons/421-4212617_person-placeholder-image-transparent-hd-png-download.png'),
}
